### ISSUE TITLE
在ios手机无法使用ai下棋

### ISSUE THREAD

**Issue by chan09060** [gomocalc/gomocalc.github.io#12]
设定了ai下白或黑棋后点击棋盘并没有反应，然后点击网页右上角发现Engine is not ready!的字句

**Comment by dhbloo** [comment]
"Engine is not ready!" 表示引擎还没有加载完成，可能是网络较慢或不稳定导致的。

你可以尝试更换浏览器，并且尝试使用一个科学上网软件（VPN）保证连接的稳定，目前网站在国内访问可能会受到一些干扰。

**Comment by chan09060** [comment]
我想应该不是网络问题因为我用安卓系统是可以连上的

**Comment by CHN1008** [comment]
same problem.
i think it is not network problem.

**Comment by dhbloo** [comment]
IOS的支持已经修复，清空浏览器缓存后重新方法，应该就可以恢复正常
