### ISSUE TITLE
请更新一下软件

### ISSUE THREAD

**Issue by a1en0924** [gomocalc/gomocalc.github.io#6]
提几个建议
1 建议增加棋力或者增加算法 如果别人先手来必胜  根本挡不住
2 增加各种开局走法 类似浦月 花月 名月之类
3  计算格子  如果花月卡格子 就用浦月
4  如果可以添加必胜或者棋谱就更好了

**Comment by dhbloo** [comment]
1. 先手必胜棋力再高也挡不住的。。
2. 开局库目前暂时不在计划中，等各项功能继续完善后会考虑
3. （不明白你的意思）
4. 想要必胜谱可以找五子棋终结者= =
