### ISSUE TITLE
安卓chrome无法正常运行

### ISSUE THREAD

**Issue by cubersm** [gomocalc/gomocalc.github.io#7]
![Screenshot_2021-01-15-20-25-46-652_com android chrome](https://user-images.githubusercontent.com/42129904/104727270-fe0a3400-576f-11eb-9b7f-8226ebec117d.jpg)

chrome点计算无法运行，系统自带浏览器可以

**Comment by dhbloo** [comment]
你好，可以先确认是否为网络问题，网络较慢时引擎加载可能在网页加载后等待一小会才完成
