### ISSUE TITLE
Buttons gone/not working

### ISSUE THREAD

**Issue by Hmku22** [gomocalc/gomocalc.github.io#8]
All of the buttons that I interacted with such as calculate next move or undo are not there. They are just blank boxes with a faint square instead of the usual buttons (like a green triangle)

**Comment by Hmku22** [comment]
Should be of note that I’ve tried multiple different browsers and multiple different devices and have had this problem every time

**Comment by dhbloo** [comment]
This seems to be a network issue. The website relies on some third party resources to display icons correctly. Please check your internet connection, or switching to a different network.

**Comment by dhbloo** [comment]
Support on iOS is now fixed. Please refresh your browser cache and it should works fine now
